//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApplication.ProductWebServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductWebServiceReference.productSoap")]
    public interface productSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoProductId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutoProductId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoProductId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AutoProductIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCategoryId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getCategoryId(string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCategoryId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getCategoryIdAsync(string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCategoryName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getCategoryName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCategoryName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getCategoryNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string insertProduct(string ProductId, string ProductName, string Price, string CategoryId, string Quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<string> insertProductAsync(string ProductId, string ProductName, string Price, string CategoryId, string Quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchProduct(string ProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchProductAsync(string ProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string updateProduct(string ProductId, string ProductName, string Price, string CategoryId, string Quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<string> updateProductAsync(string ProductId, string ProductName, string Price, string CategoryId, string Quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string deleteProduct(string ProductId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<string> deleteProductAsync(string ProductId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface productSoapChannel : AdminApplication.ProductWebServiceReference.productSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class productSoapClient : System.ServiceModel.ClientBase<AdminApplication.ProductWebServiceReference.productSoap>, AdminApplication.ProductWebServiceReference.productSoap {
        
        public productSoapClient() {
        }
        
        public productSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public productSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public productSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public productSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AutoProductId() {
            return base.Channel.AutoProductId();
        }
        
        public System.Threading.Tasks.Task<string> AutoProductIdAsync() {
            return base.Channel.AutoProductIdAsync();
        }
        
        public string getCategoryId(string CategoryName) {
            return base.Channel.getCategoryId(CategoryName);
        }
        
        public System.Threading.Tasks.Task<string> getCategoryIdAsync(string CategoryName) {
            return base.Channel.getCategoryIdAsync(CategoryName);
        }
        
        public System.Data.DataSet getCategoryName() {
            return base.Channel.getCategoryName();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getCategoryNameAsync() {
            return base.Channel.getCategoryNameAsync();
        }
        
        public string insertProduct(string ProductId, string ProductName, string Price, string CategoryId, string Quantity) {
            return base.Channel.insertProduct(ProductId, ProductName, Price, CategoryId, Quantity);
        }
        
        public System.Threading.Tasks.Task<string> insertProductAsync(string ProductId, string ProductName, string Price, string CategoryId, string Quantity) {
            return base.Channel.insertProductAsync(ProductId, ProductName, Price, CategoryId, Quantity);
        }
        
        public System.Data.DataSet SearchProduct(string ProductId) {
            return base.Channel.SearchProduct(ProductId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchProductAsync(string ProductId) {
            return base.Channel.SearchProductAsync(ProductId);
        }
        
        public string updateProduct(string ProductId, string ProductName, string Price, string CategoryId, string Quantity) {
            return base.Channel.updateProduct(ProductId, ProductName, Price, CategoryId, Quantity);
        }
        
        public System.Threading.Tasks.Task<string> updateProductAsync(string ProductId, string ProductName, string Price, string CategoryId, string Quantity) {
            return base.Channel.updateProductAsync(ProductId, ProductName, Price, CategoryId, Quantity);
        }
        
        public string deleteProduct(string ProductId) {
            return base.Channel.deleteProduct(ProductId);
        }
        
        public System.Threading.Tasks.Task<string> deleteProductAsync(string ProductId) {
            return base.Channel.deleteProductAsync(ProductId);
        }
    }
}
